FROM node

MAINTAINER Genar <genar@acs.li>

# add jessie-backports for Docker package
RUN echo "deb http://http.debian.net/debian jessie-backports main" > /etc/apt/sources.list.d/backports.list
RUN apt-get update && apt-get install -y unzip && apt-get install -y certbot -t jessie-backports

COPY . /app

WORKDIR /app

RUN npm install

ENV NODE_ENV production

ENTRYPOINT node app.js
